
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Oct  9 2026 23:49:45 EDT (Oct 10 2026 03:49:45 UTC)

// Verification Directory fv/code1 

module code1(clk, rst_n, a, b, enable, c);
  input clk, rst_n, enable;
  input [1:0] a, b;
  output [1:0] c;
  wire clk, rst_n, enable;
  wire [1:0] a, b;
  wire [1:0] c;
  wire UNCONNECTED, UNCONNECTED0, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11;
  DFFR_E \c_reg[1] (.RN (n_10), .CLK (clk), .D (n_11), .Q (c[1]), .QBAR
       (UNCONNECTED));
  AND2_H g231__2398(.A (n_9), .B (n_6), .Z (n_11));
  DFFR_E \c_reg[0] (.RN (n_10), .CLK (clk), .D (n_8), .Q (c[0]), .QBAR
       (UNCONNECTED0));
  XOR2_C g233__5107(.A (n_7), .B (n_5), .Z (n_9));
  AND3_H g234__6260(.A (n_4), .B (n_7), .C (n_6), .Z (n_8));
  XNOR2_C g235__4319(.A (n_1), .B (n_0), .Z (n_5));
  OR2_H g236__8428(.A (n_2), .B (n_3), .Z (n_4));
  NAND2BAL_E g237__5526(.A (n_3), .B (n_2), .Z (n_7));
  BUFFER_J g243(.A (a[0]), .Z (n_2));
  BUFFER_J g238(.A (enable), .Z (n_6));
  BUFFER_J g241(.A (b[0]), .Z (n_3));
  BUFFER_H g242(.A (b[1]), .Z (n_1));
  BUFFER_H g239(.A (a[1]), .Z (n_0));
  BUFFER_C g240(.A (rst_n), .Z (n_10));
endmodule

