
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Oct 10 2026 00:12:47 EDT (Oct 10 2026 04:12:47 UTC)

// Verification Directory fv/code4a 

module code4a(clk, rst_n, set_time, increment_hour, increment_minute,
     set_alarm_time, enable_alarm, alarm_off, time_hours, time_minutes,
     alarm, alarm_enabled);
  input clk, rst_n, set_time, increment_hour, increment_minute,
       set_alarm_time, enable_alarm, alarm_off;
  output [4:0] time_hours;
  output [5:0] time_minutes;
  output alarm, alarm_enabled;
  wire clk, rst_n, set_time, increment_hour, increment_minute,
       set_alarm_time, enable_alarm, alarm_off;
  wire [4:0] time_hours;
  wire [5:0] time_minutes;
  wire alarm, alarm_enabled;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire update_minutes;
  assign alarm_enabled = 1'b0;
  assign alarm = 1'b0;
  code4b U_counter(.clk (clk), .rst_n (rst_n), .update_minutes
       (update_minutes));
  DFFR_E \time_hours_q_reg[3] (.RN (rst_n), .CLK (clk), .D (n_67), .Q
       (n_77), .QBAR (UNCONNECTED));
  SDFFR_E \time_hours_q_reg[4] (.RN (rst_n), .CLK (clk), .D (n_65), .SI
       (n_0), .SE (n_20), .Q (n_78), .QBAR (UNCONNECTED0));
  NOR2_D g1246__2398(.A (n_2), .B (n_65), .Z (n_67));
  DFFR_E \time_hours_q_reg[2] (.RN (rst_n), .CLK (clk), .D (n_64), .Q
       (n_76), .QBAR (UNCONNECTED1));
  MUX21I_C g1248__5107(.D0 (n_39), .D1 (n_31), .SD (n_0), .Z (n_66));
  DFFR_E \time_minutes_q_reg[5] (.RN (rst_n), .CLK (clk), .D (n_62), .Q
       (n_73), .QBAR (n_15));
  SDFFR_E \time_hours_q_reg[1] (.RN (rst_n), .CLK (clk), .D (n_17), .SI
       (n_37), .SE (n_1), .Q (UNCONNECTED2), .QBAR (n_75));
  OA21_F g1251__6260(.A1 (n_61), .A2 (n_41), .B (n_0), .Z (n_64));
  NOR2_E g1252__4319(.A (n_63), .B (n_30), .Z (n_65));
  DFFR_E \time_hours_q_reg[0] (.RN (rst_n), .CLK (clk), .D (n_60), .Q
       (n_74), .QBAR (UNCONNECTED3));
  DFFR_E \time_minutes_q_reg[4] (.RN (rst_n), .CLK (clk), .D (n_59), .Q
       (n_72), .QBAR (n_35));
  OA21_F g1255__8428(.A1 (n_58), .A2 (n_26), .B (n_52), .Z (n_62));
  NAND2_H g1256__5526(.A (n_61), .B (n_41), .Z (n_63));
  NOR2_F g1257__6783(.A (n_1), .B (n_11), .Z (n_61));
  DFFR_E \time_minutes_q_reg[3] (.RN (rst_n), .CLK (clk), .D (n_56), .Q
       (n_71), .QBAR (UNCONNECTED4));
  OA21_F g1259__3680(.A1 (n_54), .A2 (n_40), .B (n_1), .Z (n_60));
  AOI21_B g1260__1617(.A1 (n_51), .A2 (n_25), .B (n_58), .Z (n_59));
  NOR2_E g1261__2802(.A (n_5), .B (n_25), .Z (n_58));
  DFFR_E \time_minutes_q_reg[2] (.RN (rst_n), .CLK (clk), .D (n_55), .Q
       (n_70), .QBAR (UNCONNECTED5));
  OA21_F g1263__1705(.A1 (n_8), .A2 (n_34), .B (n_5), .Z (n_56));
  NAND2_E g1264__5122(.A (n_54), .B (time_hours[0]), .Z (n_57));
  AND2_H g1265__8246(.A (n_49), .B (n_52), .Z (n_55));
  NOR2_F g1266__7098(.A (n_52), .B (n_13), .Z (n_54));
  AND2_I g1267__6131(.A (n_51), .B (n_52), .Z (n_53));
  NAND2_I g1268__1881(.A (n_50), .B (n_33), .Z (n_52));
  NAND2_F g1269__5115(.A (n_8), .B (n_7), .Z (n_51));
  DFFR_E \time_minutes_q_reg[1] (.RN (rst_n), .CLK (clk), .D (n_47), .Q
       (n_69), .QBAR (UNCONNECTED6));
  NOR3_D g1271__7482(.A (n_46), .B (n_25), .C (n_6), .Z (n_50));
  AOI21_B g1272__4733(.A1 (n_46), .A2 (n_29), .B (n_8), .Z (n_49));
  SDFFR_E \time_minutes_q_reg[0] (.RN (rst_n), .CLK (clk), .D (n_28),
       .SI (n_19), .SE (update_minutes), .Q (UNCONNECTED7), .QBAR
       (n_68));
  OA21_F g1274__6161(.A1 (n_42), .A2 (n_32), .B (n_46), .Z (n_47));
  NOR2_E g1275__9315(.A (n_46), .B (n_10), .Z (n_48));
  NAND2_I g1276__9945(.A (n_42), .B (n_32), .Z (n_46));
  NOR2_E g1278__2883(.A (n_9), .B (n_44), .Z (n_45));
  INVERT_J g1288(.A (n_75), .Z (time_hours[1]));
  INVERT_H g1295(.A (update_minutes), .Z (n_44));
  INVERT_D g1299(.A (n_26), .Z (n_43));
  INVERT_J g1306(.A (n_68), .Z (time_minutes[0]));
  BUFFER_M drc_bufs1333(.A (n_77), .Z (n_31));
  INVERT_I drc_bufs1334(.A (n_24), .Z (n_25));
  INVERT_F drc_bufs1335(.A (n_35), .Z (n_24));
  INVERT_D drc_bufs1341(.A (n_4), .Z (n_23));
  INVERT_D drc_bufs1342(.A (n_12), .Z (n_36));
  INVERT_D drc_bufs1345(.A (n_3), .Z (n_22));
  INVERT_D drc_bufs1346(.A (n_14), .Z (n_27));
  INVERT_H drc_bufs1349(.A (n_13), .Z (n_29));
  INVERT_H drc_bufs1357(.A (n_21), .Z (n_34));
  INVERT_H drc_bufs1359(.A (n_33), .Z (n_21));
  INVERT_D drc_bufs1362(.A (n_39), .Z (n_20));
  INVERT_H drc_bufs1363(.A (n_38), .Z (n_39));
  INVERT_H drc_bufs1367(.A (n_31), .Z (n_30));
  INVERT_D drc_bufs1382(.A (n_28), .Z (n_19));
  INVERT_D drc_bufs1383(.A (n_27), .Z (n_18));
  INVERT_D drc_bufs1386(.A (n_37), .Z (n_17));
  INVERT_D drc_bufs1387(.A (n_36), .Z (n_16));
  BUFFER_L drc1393(.A (n_32), .Z (time_minutes[1]));
  BUFFER_L drc1395(.A (n_41), .Z (time_hours[2]));
  BUFFER_M drc1397(.A (n_40), .Z (time_hours[0]));
  BUFFER_L drc1399(.A (n_33), .Z (time_minutes[3]));
  BUFFER_L drc1403(.A (n_38), .Z (time_hours[4]));
  BUFFER_L drc1405(.A (n_31), .Z (time_hours[3]));
  INVERT_I drc_bufs1407(.A (n_15), .Z (n_26));
  CLK_I drc1493(.A (time_hours[1]), .Z (n_12));
  CLK_I drc1498(.A (time_minutes[0]), .Z (n_14));
  BUFFER_L drc1503(.A (time_minutes[2]), .Z (n_13));
  CLK_I drc1543(.A (n_18), .Z (n_28));
  CLK_I drc1548(.A (n_16), .Z (n_37));
  CLK_I drc1570(.A (n_23), .Z (n_11));
  CLK_I drc1572(.A (n_29), .Z (n_10));
  CLK_I drc1576(.A (n_22), .Z (n_9));
  BUFFER_L drc1583(.A (n_48), .Z (n_8));
  BUFFER_L drc1593(.A (n_72), .Z (time_minutes[4]));
  CLK_I drc1601(.A (n_34), .Z (n_7));
  CLK_I drc1605(.A (n_43), .Z (n_6));
  BUFFER_J drc1610(.A (n_53), .Z (n_5));
  BUFFER_F drc1614(.A (n_12), .Z (n_4));
  BUFFER_F drc1622(.A (n_14), .Z (n_3));
  BUFFER_M drc1657(.A (n_26), .Z (time_minutes[5]));
  BUFFER_L drc1662(.A (n_45), .Z (n_42));
  BUFFER_M drc1667(.A (n_69), .Z (n_32));
  BUFFER_M drc1672(.A (n_76), .Z (n_41));
  BUFFER_M drc1677(.A (n_71), .Z (n_33));
  BUFFER_M drc1682(.A (n_70), .Z (time_minutes[2]));
  BUFFER_L drc1687(.A (n_74), .Z (n_40));
  BUFFER_L drc1694(.A (n_78), .Z (n_38));
  BUFFER_L drc1699(.A (n_57), .Z (n_1));
  BUFFER_K drc1704(.A (n_63), .Z (n_0));
  BUFFER_H drc1706(.A (n_66), .Z (n_2));
endmodule

