
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Oct  9 2026 22:30:07 EDT (Oct 10 2026 02:30:07 UTC)

// Verification Directory fv/code3 

module code3(clk, rst_n, in1, in2, out1, out2);
  input clk, rst_n, in1, in2;
  output out1, out2;
  wire clk, rst_n, in1, in2;
  wire out1, out2;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, mid1,
       mid2, n_0, n_1;
  wire n_2;
  DFFR_E out1_reg(.RN (n_2), .CLK (clk), .D (mid1), .Q (out1), .QBAR
       (UNCONNECTED));
  DFFR_E out2_reg(.RN (n_2), .CLK (clk), .D (mid2), .Q (out2), .QBAR
       (UNCONNECTED0));
  DFFR_E mid2_reg(.RN (n_2), .CLK (clk), .D (n_1), .Q (mid2), .QBAR
       (UNCONNECTED1));
  DFFR_E mid1_reg(.RN (n_2), .CLK (clk), .D (n_0), .Q (mid1), .QBAR
       (UNCONNECTED2));
  BUFFER_C g13(.A (rst_n), .Z (n_2));
  BUFFER_H g11(.A (in2), .Z (n_1));
  BUFFER_H g12(.A (in1), .Z (n_0));
endmodule

