
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Oct  1 2026 19:45:13 EDT (Oct  1 2026 23:45:13 UTC)

// Verification Directory fv/program_counter 

module program_counter(clk, rst_n, update_msbs, update_lsbs, jump,
     jump_destination, branch, branch_offset, mem_addr);
  input clk, rst_n, update_msbs, update_lsbs, jump, branch;
  input [5:0] jump_destination, branch_offset;
  output [7:0] mem_addr;
  wire clk, rst_n, update_msbs, update_lsbs, jump, branch;
  wire [5:0] jump_destination, branch_offset;
  wire [7:0] mem_addr;
  wire [5:0] jump_destination_q;
  wire [5:0] branch_offset_q;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire branch_q, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84;
  DFFR_H \mem_addr_reg[7] (.RN (n_75), .CLK (clk), .D (n_76), .Q
       (mem_addr[7]), .QBAR (UNCONNECTED));
  AO222_D g4630__2398(.A1 (n_70), .A2 (n_73), .B1 (n_72), .B2 (n_47),
       .C1 (n_71), .C2 (jump_destination_q[5]), .Z (n_76));
  DFFR_H \mem_addr_reg[6] (.RN (n_75), .CLK (clk), .D (n_74), .Q
       (mem_addr[6]), .QBAR (UNCONNECTED0));
  AO222_D g4632__5107(.A1 (n_69), .A2 (n_73), .B1 (n_72), .B2 (n_67),
       .C1 (n_71), .C2 (jump_destination_q[4]), .Z (n_74));
  XNOR2_C g4633__6260(.A (n_68), .B (n_48), .Z (n_70));
  ADDF_F g4634__4319(.A (n_42), .B (n_67), .CIN (n_64), .COUT (n_68),
       .SUM (n_69));
  DFFR_H \mem_addr_reg[5] (.RN (n_75), .CLK (clk), .D (n_66), .Q
       (mem_addr[5]), .QBAR (UNCONNECTED1));
  AO222_D g4636__8428(.A1 (n_65), .A2 (n_73), .B1 (n_72), .B2 (n_63),
       .C1 (n_71), .C2 (jump_destination_q[3]), .Z (n_66));
  ADDF_F g4637__5526(.A (n_37), .B (n_63), .CIN (n_60), .COUT (n_64),
       .SUM (n_65));
  DFFR_H \mem_addr_reg[4] (.RN (n_75), .CLK (clk), .D (n_62), .Q
       (mem_addr[4]), .QBAR (UNCONNECTED2));
  AO222_D g4639__6783(.A1 (n_61), .A2 (n_73), .B1 (n_72), .B2 (n_59),
       .C1 (n_71), .C2 (jump_destination_q[2]), .Z (n_62));
  DFFR_H \mem_addr_reg[2] (.RN (n_75), .CLK (clk), .D (n_58), .Q
       (mem_addr[2]), .QBAR (UNCONNECTED3));
  ADDF_F g4641__3680(.A (n_32), .B (n_59), .CIN (n_51), .COUT (n_60),
       .SUM (n_61));
  DFFR_H \mem_addr_reg[3] (.RN (n_75), .CLK (clk), .D (n_57), .Q
       (mem_addr[3]), .QBAR (UNCONNECTED4));
  OA21_F g4645__1617(.A1 (n_18), .A2 (n_54), .B (n_53), .Z (n_58));
  DFFR_H \mem_addr_reg[0] (.RN (n_75), .CLK (clk), .D (n_56), .Q
       (mem_addr[0]), .QBAR (UNCONNECTED5));
  DFFR_H \mem_addr_reg[1] (.RN (n_75), .CLK (clk), .D (n_55), .Q
       (mem_addr[1]), .QBAR (UNCONNECTED6));
  AO222_D g4642__2802(.A1 (n_52), .A2 (n_73), .B1 (n_72), .B2 (n_50),
       .C1 (n_71), .C2 (jump_destination_q[1]), .Z (n_57));
  AND3_H g4648__1705(.A (n_45), .B (n_43), .C (n_72), .Z (n_56));
  AND2_H g4649__5122(.A (n_46), .B (n_72), .Z (n_55));
  AOI21_B g4650__8246(.A1 (n_39), .A2 (n_27), .B (n_72), .Z (n_54));
  AOI22_B g4651__7098(.A1 (n_49), .A2 (n_73), .B1 (n_71), .B2
       (jump_destination_q[0]), .Z (n_53));
  ADDF_F g4644__6131(.A (n_25), .B (n_50), .CIN (n_49), .COUT (n_51),
       .SUM (n_52));
  NOR2_J g4652__1881(.A (n_73), .B (n_34), .Z (n_72));
  XOR2_C g4655__5115(.A (n_44), .B (n_47), .Z (n_48));
  NAND2_K g4653__7482(.A (n_38), .B (n_41), .Z (n_73));
  XNOR2_C g4654__4733(.A (n_1), .B (n_45), .Z (n_46));
  NOR3_F g4659__6161(.A (n_31), .B (n_33), .C (n_40), .Z (n_71));
  NAND2_D g4665__9315(.A (branch_offset_q[5]), .B (n_36), .Z (n_44));
  OR2_H g4661__9945(.A (n_20), .B (n_30), .Z (n_43));
  NOR2_D g4663__2883(.A (n_35), .B (n_80), .Z (n_42));
  INVERT_I g4684(.A (n_40), .Z (n_41));
  INVERT_F g4657(.A (n_38), .Z (n_39));
  NAND2BAL_E g4664__2346(.A (n_19), .B (n_29), .Z (n_45));
  NOR2_D g4666__1666(.A (n_28), .B (n_81), .Z (n_37));
  INVERT_H g4686(.A (n_35), .Z (n_36));
  BUFFER_L g4685(.A (n_35), .Z (n_40));
  NOR2_F g4668__7410(.A (n_33), .B (n_22), .Z (n_34));
  NOR2_D g4669__6417(.A (n_24), .B (n_82), .Z (n_32));
  NAND3_H g4658__5477(.A (n_31), .B (n_21), .C (branch_q), .Z (n_38));
  BUFFER_H g4671(.A (n_29), .Z (n_30));
  NOR2_F g4656__2398(.A (n_17), .B (n_26), .Z (n_49));
  BUFFER_L g4687(.A (n_28), .Z (n_35));
  BUFFER_H g4660(.A (n_26), .Z (n_27));
  NOR2_D g4667__5107(.A (n_23), .B (n_83), .Z (n_25));
  BUFFER_J g4672(.A (n_33), .Z (n_29));
  BUFFER_J g4688(.A (n_24), .Z (n_28));
  BUFFER_J g4689(.A (n_23), .Z (n_24));
  NOR2_F g4662__6260(.A (n_79), .B (n_84), .Z (n_26));
  BUFFER_J g4670(.A (n_31), .Z (n_22));
  INVERT_K g4673(.A (n_21), .Z (n_33));
  INVERT_K g4681(.A (n_78), .Z (n_31));
  INVERT_J g4683(.A (n_77), .Z (n_21));
  BUFFER_J g4690(.A (n_79), .Z (n_23));
  DFFR_E branch_q_reg(.RN (n_75), .CLK (clk), .D (n_5), .Q (branch_q),
       .QBAR (UNCONNECTED7));
  DFFR_E update_lsbs_q_reg(.RN (n_75), .CLK (clk), .D (n_6), .Q (n_77),
       .QBAR (UNCONNECTED8));
  DFFR_E \branch_offset_q_reg[3] (.RN (n_75), .CLK (clk), .D (n_12), .Q
       (UNCONNECTED9), .QBAR (n_81));
  DFFR_E \branch_offset_q_reg[0] (.RN (n_75), .CLK (clk), .D (n_9), .Q
       (n_84), .QBAR (UNCONNECTED10));
  DFFR_E \jump_destination_q_reg[2] (.RN (n_75), .CLK (clk), .D (n_7),
       .Q (jump_destination_q[2]), .QBAR (UNCONNECTED11));
  DFFR_E \branch_offset_q_reg[4] (.RN (n_75), .CLK (clk), .D (n_15), .Q
       (UNCONNECTED12), .QBAR (n_80));
  DFFR_E \jump_destination_q_reg[3] (.RN (n_75), .CLK (clk), .D (n_0),
       .Q (jump_destination_q[3]), .QBAR (UNCONNECTED13));
  DFFR_E \jump_destination_q_reg[1] (.RN (n_75), .CLK (clk), .D (n_3),
       .Q (jump_destination_q[1]), .QBAR (UNCONNECTED14));
  DFFR_E \branch_offset_q_reg[2] (.RN (n_75), .CLK (clk), .D (n_11), .Q
       (UNCONNECTED15), .QBAR (n_82));
  DFFR_E \branch_offset_q_reg[5] (.RN (n_75), .CLK (clk), .D (n_4), .Q
       (branch_offset_q[5]), .QBAR (UNCONNECTED16));
  DFFR_E \jump_destination_q_reg[0] (.RN (n_75), .CLK (clk), .D (n_10),
       .Q (UNCONNECTED17), .QBAR (jump_destination_q[0]));
  DFFR_H jump_q_reg(.RN (n_75), .CLK (clk), .D (n_14), .Q (n_78), .QBAR
       (UNCONNECTED18));
  DFFR_E \jump_destination_q_reg[4] (.RN (n_75), .CLK (clk), .D (n_13),
       .Q (jump_destination_q[4]), .QBAR (UNCONNECTED19));
  DFFR_E \jump_destination_q_reg[5] (.RN (n_75), .CLK (clk), .D (n_16),
       .Q (jump_destination_q[5]), .QBAR (UNCONNECTED20));
  DFFR_E \branch_offset_q_reg[1] (.RN (n_75), .CLK (clk), .D (n_8), .Q
       (UNCONNECTED21), .QBAR (n_83));
  DFFR_H update_msbs_q_reg(.RN (n_75), .CLK (clk), .D (n_2), .Q (n_79),
       .QBAR (UNCONNECTED22));
  BUFFER_F g4708(.A (n_19), .Z (n_20));
  INVERT_D g4719(.A (n_17), .Z (n_18));
  BUFFER_H g4699(.A (jump_destination[5]), .Z (n_16));
  BUFFER_H g4706(.A (branch_offset[4]), .Z (n_15));
  BUFFER_H g4702(.A (jump), .Z (n_14));
  BUFFER_H g4715(.A (jump_destination[4]), .Z (n_13));
  BUFFER_H g4717(.A (branch_offset[3]), .Z (n_12));
  BUFFER_H g4716(.A (branch_offset[2]), .Z (n_11));
  BUFFER_H g4701(.A (jump_destination[0]), .Z (n_10));
  BUFFER_H g4714(.A (branch_offset[0]), .Z (n_9));
  BUFFER_J g4710(.A (mem_addr[5]), .Z (n_63));
  INVERT_H g4720(.A (mem_addr[2]), .Z (n_17));
  BUFFER_J g4724(.A (mem_addr[6]), .Z (n_67));
  BUFFER_C g4711(.A (rst_n), .Z (n_75));
  BUFFER_H g4703(.A (branch_offset[1]), .Z (n_8));
  BUFFER_H g4700(.A (jump_destination[2]), .Z (n_7));
  BUFFER_H g4707(.A (update_lsbs), .Z (n_6));
  BUFFER_H g4704(.A (branch), .Z (n_5));
  BUFFER_H g4705(.A (branch_offset[5]), .Z (n_4));
  BUFFER_H g4712(.A (jump_destination[1]), .Z (n_3));
  BUFFER_H g4718(.A (update_msbs), .Z (n_2));
  BUFFER_H g4721(.A (mem_addr[1]), .Z (n_1));
  BUFFER_H g4713(.A (jump_destination[3]), .Z (n_0));
  BUFFER_J g4723(.A (mem_addr[4]), .Z (n_59));
  BUFFER_J g4725(.A (mem_addr[3]), .Z (n_50));
  BUFFER_I g4722(.A (mem_addr[7]), .Z (n_47));
  BUFFER_J g4709(.A (mem_addr[0]), .Z (n_19));
endmodule

