
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Oct  1 2026 19:19:53 EDT (Oct  1 2026 23:19:53 UTC)

// Verification Directory fv/program_counter 

module program_counter(clk, rst_n, update_msbs, update_lsbs, jump,
     jump_destination, branch, branch_offset, mem_addr);
  input clk, rst_n, update_msbs, update_lsbs, jump, branch;
  input [5:0] jump_destination, branch_offset;
  output [7:0] mem_addr;
  wire clk, rst_n, update_msbs, update_lsbs, jump, branch;
  wire [5:0] jump_destination, branch_offset;
  wire [7:0] mem_addr;
  wire [5:0] jump_destination_q;
  wire [5:0] branch_offset_q;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire branch_q, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, update_lsbs_q, update_msbs_q;
  DFFR_H \mem_addr_reg[7] (.RN (n_72), .CLK (clk), .D (n_73), .Q
       (mem_addr[7]), .QBAR (UNCONNECTED));
  AO222_D g1851__2398(.A1 (n_67), .A2 (n_70), .B1 (n_69), .B2 (n_46),
       .C1 (n_68), .C2 (jump_destination_q[5]), .Z (n_73));
  DFFR_H \mem_addr_reg[6] (.RN (n_72), .CLK (clk), .D (n_71), .Q
       (mem_addr[6]), .QBAR (UNCONNECTED0));
  AO222_D g1853__5107(.A1 (n_66), .A2 (n_70), .B1 (n_69), .B2 (n_64),
       .C1 (n_68), .C2 (jump_destination_q[4]), .Z (n_71));
  XNOR2_C g1854__6260(.A (n_65), .B (n_47), .Z (n_67));
  ADDF_F g1855__4319(.A (n_37), .B (n_64), .CIN (n_61), .COUT (n_65),
       .SUM (n_66));
  DFFR_H \mem_addr_reg[5] (.RN (n_72), .CLK (clk), .D (n_63), .Q
       (mem_addr[5]), .QBAR (UNCONNECTED1));
  AO222_D g1857__8428(.A1 (n_62), .A2 (n_70), .B1 (n_69), .B2 (n_60),
       .C1 (n_68), .C2 (jump_destination_q[3]), .Z (n_63));
  ADDF_F g1859__5526(.A (n_33), .B (n_60), .CIN (n_57), .COUT (n_61),
       .SUM (n_62));
  DFFR_H \mem_addr_reg[4] (.RN (n_72), .CLK (clk), .D (n_59), .Q
       (mem_addr[4]), .QBAR (UNCONNECTED2));
  AO222_D g1860__6783(.A1 (n_58), .A2 (n_70), .B1 (n_69), .B2 (n_56),
       .C1 (n_68), .C2 (jump_destination_q[2]), .Z (n_59));
  ADDF_F g1861__3680(.A (n_29), .B (n_56), .CIN (n_49), .COUT (n_57),
       .SUM (n_58));
  DFFR_H \mem_addr_reg[3] (.RN (n_72), .CLK (clk), .D (n_55), .Q
       (mem_addr[3]), .QBAR (UNCONNECTED3));
  DFFR_H \mem_addr_reg[2] (.RN (n_72), .CLK (clk), .D (n_54), .Q
       (mem_addr[2]), .QBAR (UNCONNECTED4));
  DFFR_H \mem_addr_reg[0] (.RN (n_72), .CLK (clk), .D (n_52), .Q
       (mem_addr[0]), .QBAR (UNCONNECTED5));
  AO222_D g1864__1617(.A1 (n_50), .A2 (n_70), .B1 (n_69), .B2 (n_48),
       .C1 (n_68), .C2 (jump_destination_q[1]), .Z (n_55));
  OAI21_B g1865__2802(.A1 (n_41), .A2 (n_45), .B (n_53), .Z (n_54));
  DFFR_H \mem_addr_reg[1] (.RN (n_72), .CLK (clk), .D (n_51), .Q
       (mem_addr[1]), .QBAR (UNCONNECTED6));
  AOI22_B g1868__1705(.A1 (n_40), .A2 (n_69), .B1 (n_68), .B2
       (jump_destination_q[0]), .Z (n_53));
  AND3_H g1870__5122(.A (n_38), .B (n_31), .C (n_69), .Z (n_52));
  AND2_H g1871__8246(.A (n_39), .B (n_69), .Z (n_51));
  ADDF_F g1866__7098(.A (n_25), .B (n_48), .CIN (n_35), .COUT (n_49),
       .SUM (n_50));
  NOR2_J g1872__6131(.A (n_70), .B (n_24), .Z (n_69));
  XOR2_C g1877__1881(.A (n_44), .B (n_46), .Z (n_47));
  NOR3_F g1881__5115(.A (n_26), .B (n_23), .C (n_43), .Z (n_68));
  INVERT_D g1873(.A (n_70), .Z (n_45));
  NAND2_K g1875__7482(.A (n_27), .B (n_42), .Z (n_70));
  NAND2_D g1883__4733(.A (branch_offset_q[5]), .B (n_36), .Z (n_44));
  INVERT_H g1901(.A (n_42), .Z (n_43));
  OAI21_B g1874__6161(.A1 (n_40), .A2 (n_30), .B (n_34), .Z (n_41));
  XNOR2_C g1876__9315(.A (n_12), .B (n_38), .Z (n_39));
  NOR2_D g1889__9945(.A (n_32), .B (branch_offset_q[4]), .Z (n_37));
  BUFFER_M g1902(.A (n_36), .Z (n_42));
  INVERT_H g1878(.A (n_34), .Z (n_35));
  NOR2_D g1888__2883(.A (n_28), .B (branch_offset_q[3]), .Z (n_33));
  INVERT_I g1903(.A (n_32), .Z (n_36));
  OR2_H g1882__2346(.A (n_19), .B (n_21), .Z (n_31));
  NAND2_F g1879__1666(.A (n_17), .B (n_30), .Z (n_34));
  NOR2_D g1887__7410(.A (n_22), .B (branch_offset_q[2]), .Z (n_29));
  BUFFER_J g1904(.A (n_28), .Z (n_32));
  NAND3_F g1880__6417(.A (n_26), .B (update_lsbs_q), .C (branch_q), .Z
       (n_27));
  NOR2_D g1884__5477(.A (n_20), .B (branch_offset_q[1]), .Z (n_25));
  NOR2_F g1886__2398(.A (n_23), .B (n_26), .Z (n_24));
  NAND2BAL_E g1885__5107(.A (n_18), .B (n_23), .Z (n_38));
  BUFFER_J g1905(.A (n_22), .Z (n_28));
  NAND2_F g1890__6260(.A (update_msbs_q), .B (branch_offset_q[0]), .Z
       (n_30));
  BUFFER_F g1899(.A (n_23), .Z (n_21));
  BUFFER_J g1906(.A (n_20), .Z (n_22));
  INVERT_H g1907(.A (update_msbs_q), .Z (n_20));
  INVERT_K g1914(.A (n_74), .Z (n_26));
  INVERT_K g1900(.A (update_lsbs_q), .Z (n_23));
  DFFR_E \jump_destination_q_reg[5] (.RN (n_72), .CLK (clk), .D (n_8),
       .Q (jump_destination_q[5]), .QBAR (UNCONNECTED7));
  DFFR_E \jump_destination_q_reg[4] (.RN (n_72), .CLK (clk), .D (n_1),
       .Q (jump_destination_q[4]), .QBAR (UNCONNECTED8));
  DFFR_E \branch_offset_q_reg[1] (.RN (n_72), .CLK (clk), .D (n_11), .Q
       (UNCONNECTED9), .QBAR (branch_offset_q[1]));
  DFFR_E \branch_offset_q_reg[5] (.RN (n_72), .CLK (clk), .D (n_9), .Q
       (branch_offset_q[5]), .QBAR (UNCONNECTED10));
  DFFR_E \jump_destination_q_reg[2] (.RN (n_72), .CLK (clk), .D (n_4),
       .Q (jump_destination_q[2]), .QBAR (UNCONNECTED11));
  DFFR_E \jump_destination_q_reg[3] (.RN (n_72), .CLK (clk), .D (n_14),
       .Q (jump_destination_q[3]), .QBAR (UNCONNECTED12));
  DFFR_E branch_q_reg(.RN (n_72), .CLK (clk), .D (n_3), .Q (branch_q),
       .QBAR (UNCONNECTED13));
  DFFR_E \jump_destination_q_reg[1] (.RN (n_72), .CLK (clk), .D (n_5),
       .Q (jump_destination_q[1]), .QBAR (UNCONNECTED14));
  DFFR_E \branch_offset_q_reg[2] (.RN (n_72), .CLK (clk), .D (n_10), .Q
       (UNCONNECTED15), .QBAR (branch_offset_q[2]));
  DFFR_E \branch_offset_q_reg[4] (.RN (n_72), .CLK (clk), .D (n_6), .Q
       (UNCONNECTED16), .QBAR (branch_offset_q[4]));
  DFFR_E \branch_offset_q_reg[3] (.RN (n_72), .CLK (clk), .D (n_0), .Q
       (UNCONNECTED17), .QBAR (branch_offset_q[3]));
  DFFR_E \branch_offset_q_reg[0] (.RN (n_72), .CLK (clk), .D (n_15), .Q
       (UNCONNECTED18), .QBAR (branch_offset_q[0]));
  DFFR_E \jump_destination_q_reg[0] (.RN (n_72), .CLK (clk), .D (n_13),
       .Q (jump_destination_q[0]), .QBAR (UNCONNECTED19));
  DFFR_H jump_q_reg(.RN (n_72), .CLK (clk), .D (n_7), .Q (n_74), .QBAR
       (UNCONNECTED20));
  DFFR_H update_msbs_q_reg(.RN (n_72), .CLK (clk), .D (n_16), .Q
       (UNCONNECTED21), .QBAR (update_msbs_q));
  DFFR_H update_lsbs_q_reg(.RN (n_72), .CLK (clk), .D (n_2), .Q
       (UNCONNECTED22), .QBAR (update_lsbs_q));
  BUFFER_F g1922(.A (n_18), .Z (n_19));
  BUFFER_I g1926(.A (n_17), .Z (n_40));
  BUFFER_H g1919(.A (update_msbs), .Z (n_16));
  BUFFER_H g1931(.A (branch_offset[0]), .Z (n_15));
  BUFFER_H g1938(.A (jump_destination[3]), .Z (n_14));
  BUFFER_H g1936(.A (jump_destination[0]), .Z (n_13));
  BUFFER_H g1924(.A (mem_addr[1]), .Z (n_12));
  BUFFER_H g1940(.A (branch_offset[1]), .Z (n_11));
  BUFFER_H g1920(.A (branch_offset[2]), .Z (n_10));
  BUFFER_H g1935(.A (branch_offset[5]), .Z (n_9));
  BUFFER_H g1917(.A (jump_destination[5]), .Z (n_8));
  BUFFER_H g1937(.A (jump), .Z (n_7));
  BUFFER_J g1929(.A (mem_addr[6]), .Z (n_64));
  BUFFER_J g1943(.A (mem_addr[4]), .Z (n_56));
  BUFFER_H g1933(.A (branch_offset[4]), .Z (n_6));
  BUFFER_H g1939(.A (jump_destination[1]), .Z (n_5));
  BUFFER_H g1921(.A (jump_destination[2]), .Z (n_4));
  BUFFER_H g1941(.A (branch), .Z (n_3));
  BUFFER_H g1918(.A (update_lsbs), .Z (n_2));
  BUFFER_H g1932(.A (jump_destination[4]), .Z (n_1));
  BUFFER_H g1934(.A (branch_offset[3]), .Z (n_0));
  BUFFER_J g1925(.A (mem_addr[5]), .Z (n_60));
  BUFFER_J g1927(.A (mem_addr[2]), .Z (n_17));
  BUFFER_J g1928(.A (mem_addr[3]), .Z (n_48));
  BUFFER_I g1942(.A (mem_addr[7]), .Z (n_46));
  BUFFER_J g1923(.A (mem_addr[0]), .Z (n_18));
  BUFFER_C g1930(.A (rst_n), .Z (n_72));
endmodule

