#!/bin/bash

# list of design files to be compiled


ver_files=(
           "../../source/elevator_controller.sv"
           "../testbench/elevator_controller_tb.sv"
	   "../../source/elevator_fsm.sv"
	   "../../source/elevator_button.sv")
