#!/bin/bash

# list of design files to be compiled


ver_files=(
           "../../source/elevator_controller.v"
           "../testbench/elevator_controller_tb.v"
	   "../../source/elevator_fsm.v"
	   "../../source/elevator_button.v")
