
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Oct  5 2026 15:42:30 EDT (Oct  5 2026 19:42:30 UTC)

// Verification Directory fv/code2 

module code2(clk, rst_n, quarter_inserted, button_pressed, vend_cola);
  input clk, rst_n, quarter_inserted, button_pressed;
  output vend_cola;
  wire clk, rst_n, quarter_inserted, button_pressed;
  wire vend_cola;
  assign vend_cola = 1'b1;
endmodule

