
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Oct  9 2026 20:30:46 EDT (Oct 10 2026 00:30:46 UTC)

// Verification Directory fv/code2 

module code2(clk, rst_n, quarter_inserted, button_pressed, vend_cola);
  input clk, rst_n, quarter_inserted, button_pressed;
  output vend_cola;
  wire clk, rst_n, quarter_inserted, button_pressed;
  wire vend_cola;
  wire [1:0] state_current;
  wire UNCONNECTED, UNCONNECTED0, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17;
  DFFR_H \state_current_reg[0] (.RN (n_16), .CLK (clk), .D (n_17), .Q
       (UNCONNECTED), .QBAR (state_current[0]));
  OAI21_B g287__2398(.A1 (n_11), .A2 (n_10), .B (n_15), .Z (n_17));
  DFFR_H \state_current_reg[1] (.RN (n_16), .CLK (clk), .D (n_14), .Q
       (UNCONNECTED0), .QBAR (state_current[1]));
  OAI21_B g289__5107(.A1 (n_12), .A2 (n_9), .B (n_13), .Z (n_15));
  NOR2_D g288__6260(.A (n_13), .B (n_7), .Z (n_14));
  AOI21_D g290__4319(.A1 (n_12), .A2 (n_2), .B (n_4), .Z (n_13));
  NAND2_D g293__8428(.A (n_0), .B (n_5), .Z (n_11));
  INVERT_D g300(.A (n_8), .Z (n_10));
  INVERT_H g301(.A (n_8), .Z (n_9));
  BUFFER_H g291(.A (vend_cola), .Z (n_7));
  INVERT_D g295(.A (n_3), .Z (n_5));
  INVERT_H g296(.A (n_3), .Z (n_4));
  INVERT_H g303(.A (n_1), .Z (n_2));
  BUFFER_J g302(.A (n_1), .Z (n_8));
  NOR2_F g292__5526(.A (state_current[0]), .B (state_current[1]), .Z
       (vend_cola));
  BUFFER_C g294(.A (rst_n), .Z (n_16));
  BUFFER_J g304(.A (state_current[0]), .Z (n_1));
  BUFFER_H g298(.A (button_pressed), .Z (n_0));
  BUFFER_J g299(.A (quarter_inserted), .Z (n_12));
  BUFFER_J g297(.A (state_current[1]), .Z (n_3));
endmodule

