
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Oct  9 2026 20:25:07 EDT (Oct 10 2026 00:25:07 UTC)

// Verification Directory fv/code0 

module code0(clk, rst_n, a, b, c);
  input clk, rst_n, a, b;
  output c;
  wire clk, rst_n, a, b;
  wire c;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4;
  DFFR_H c_reg(.RN (n_3), .CLK (clk), .D (n_4), .Q (c), .QBAR
       (UNCONNECTED));
  OA21_F g82__2398(.A1 (n_0), .A2 (n_1), .B (n_2), .Z (n_4));
  BUFFER_C g83(.A (rst_n), .Z (n_3));
  INVERT_H g85(.A (b), .Z (n_2));
  BUFFER_H g84(.A (c), .Z (n_1));
  BUFFER_H g86(.A (a), .Z (n_0));
endmodule

